<expression>     ::= <term> | <term> <expression>
<term>          ::= <factor> <quantifier>?
<factor>        ::= <char> | "." | <escaped_char> | "[" <char_class> "]"
<char_class>    ::= <char_class_item>+
<char_class_item> ::= <char> | <escaped_char> | "."
<char>          ::= [a-z]
<escaped_char>  ::= "\\s" | "\\S"
<quantifier>    ::= "*"
