Regex           ::= Expression+
Expression      ::= Term+
Term            ::= Factor Quantifier?
Factor          ::= Char | '[' CharClass ']' | '.' | EscapedChar
CharClass       ::= CharClassItem+
CharClassItem   ::= Char | EscapedChar
EscapedChar     ::= '\\s' | '\\S'
Char            ::= [a-z]
Quantifier      ::= '*'
